[project]
name = "lilypond-files"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "htpy>=25.4.2",
    "lilypond<2.25",
    "python-ly>=0.9.9",
]
